gengo:
  - name: 令和
    start_date: 2019-05-01
  - name: 平成
    start_date: 1989-01-08
  - name: 昭和
    start_date: 1926-12-25
  - name: 大正
    start_date: 1912-07-30
# タイムスタンプが生成出来ない。
# - name: 明治
#   start_date: 1868-09-08

holiday:
  ja:
    class: GoogleJapaneseHolidayListService
