# メニュー設定ファイル - 管理メニュー
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>

- separator: yes
- module: AdminLog
- module: AdminMemcache
  href: /AdminMemcache/?pane=default_pane
  target: _self
- module: AdminTableReport
- separator: yes
- title: ログアウト
  module: Default
  action: Logout