# フィルタ設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>

- class: LegacyUserAgentFilter
- class: EncodingRequestFilter
- class: NewLineRequestFilter
- class: CookieFilter
  params:
    excluded_actions:
      - Login
