app:
  name:
    ja: __NAME_JA__
    en: __NAME_EN__
  ver: 1.0.0-dev

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp
crypt:
  password: __YOUR_PASSWORD__
  digest:
    salt: __YOUR_SALT__
service:
  google:
    analytics:
      id: 0000000-00 # 先頭の "UA-" は含めない。
