# アプリケーション定数設定ファイル - carrot分
#
# @package jp.co.b-shock.carrot3
# @author 小石達也 <tkoishi@b-shock.co.jp>

carrot:
  name: carrot Framework
  ver: 3.0.50

admin:
  email:
  password:
  networks:
  twitter: pooza
app:
  deploy:
    dir:
      freebsd: /usr/local/www/apache24/data
  name:
    ja: unknown
    en: unknown
  ver: unknown
  memory_limit: 256M
  time_limit: 120
  memory_limit_max: 1G
  time_limit_max: 0
  http_cache:
    mode: private
    seconds: 60
  process:
    uid:
      default: nobody
      freebsd: www
      ubuntu: www-data
author:
  name:
  email:
  password:
  twitter: carrot_fw
backup:
  class: BackupManager
clamav:
  command: clamdscan
  dir:
    default: /usr/local
    ubuntu: /usr
crypt:
  engine: open_ssl
  method: AES-256-CBC
  password: __YOUR_PASSWORD__
  digest:
    method: sha1
    salt: __YOUR_SALT__
date:
  timezone: Asia/Tokyo
debug: yes
ffmpeg:
  dir:
    default: /usr/local
    ubuntu: /usr
  convert:
    mp4:
      video_codec: libx264
      audio_codec: aac
    jpg:
      ss: 2
      vframes: 1
    png:
      ss: 2
      vframes: 1
    webm:
      audio_codec: libvorbis
      audio_sampling_frequency: 44100
    mp3:
geocode:
  map:
    function: CarrotMapsLib.handleMap
image:
  renderers:
    default:
      class: Image
  mobile:
    size:
      qvga:
        width: 240
        height: 320
      vga:
        width: 480
        height: 640
  qrcode:
    size: 80
  thumbnail:
    bgcolor: black
    type: image/png
  apple_icon:
    pixels: 57
  favicon:
    pixels: 16
image_magick:
  dir:
    default: /usr/local
    ubuntu: /usr
languages:
  - ja
log:
  loggers:
    - System
logger:
  dir:
    default: /usr
mail:
  sender: Sendmail
memcache:
  default:
    host: /tmp/memcached.sock
    port: 0
  render:
    host: /tmp/memcached_render.sock
    port: 0
module:
  cache_parameters: yes
  prefixes:
    - Admin
    - User
    - Agent
    - Console
  default:
    module: Default
    action: Default
  not_found:
    module: Default
    action: NotFound
  secure:
    module: Default
    action: Forbidden
  empty_site:
    module: Default
    action: EmptySite
  legacy_user_agent:
    module: Default
    action: DeniedUserAgent
mysql:
  dir:
    default: /usr/local
    ubuntu: /usr
net:
  url:
    shorter: google_url_shortner
package:
  name:
  ver:
periodic:
  development:
    frequently:
    hourly:
    daily:
      - Console:Purge
  production:
    frequently:
    hourly:
    daily:
      - Console:Purge
pdo:
  default:
    dsn: sqlite:%BS_VAR_DIR%/db/default.sqlite3
    loggable: yes
  serialize:
    dsn: sqlite:%BS_VAR_DIR%/db/serialize.sqlite3
pgsql:
  dir:
    default: /usr/local
    ubuntu: /usr
php:
  dir:
    default: /usr/local
    ubuntu: /usr
pictogram:
proctools:
  dir:
    default: /usr
pw:
  dir:
    freebsd: /usr
render:
  storage: Memcache
ruby:
  dir:
    default: /usr/local
    ubuntu: /usr
sendmail:
  dir:
    default: /usr
serialize:
  storage: Memcache
  serializer: JSON
  classes:
service:
  bitly:
    version: 2.0.1
    login: carrotfw
    api_key: R_dbbb70d7b5959e23289acfc3458f836f
  google:
    maps:
      api_key: AIzaSyAmndtwEGM1gFl1fBHYo4jK2OKqEls0-Dg
      zoom: 17
    static_maps:
      api_key: AIzaSyAmndtwEGM1gFl1fBHYo4jK2OKqEls0-Dg
      format: gif
    maps_geocoding:
      api_key: AIzaSyAmndtwEGM1gFl1fBHYo4jK2OKqEls0-Dg
    analytics:
      id:
    calendar:
      api_key: AIzaSyAmndtwEGM1gFl1fBHYo4jK2OKqEls0-Dg
    url_shortener:
      api_key: AIzaSyAmndtwEGM1gFl1fBHYo4jK2OKqEls0-Dg
  twitter:
    consumer:
      key: hhXdKP3kEwvWumb1AFbTlQ
      secret: m5dkKU4xnuLfD5WHOpctisvR08rSfB80x9Bfy0nnlk
    access_token: 139985635-LEKAX9Soa2zrjjtOf0MWR8KQdFJM8cGCgX7myMo
    access_token_secret: MfGm4toy0En5ZntHJFt6O4xOcZzAnfwnW9rDUaY
    minutes: 5
  slack:
    webhook:
      url: /services/T818MGY3S/B8A93KZL2/L5StOlVmm3Apqd0NED9zQUWJ
session:
  storage: Memcache
smtp:
  host:
  timeout: 200000 #ミリ秒単位
sqlite3:
  dir:
    default: /usr/local
    ubuntu: /usr
sudo:
  dir:
    default: /usr
    freebsd: /usr/local
tidy5:
  dir:
    default: /usr/local
    ubuntu: /usr
unzip:
  dir:
    default: /usr
user:
  class: Carrot3\User
view:
  frame_options: sameorigin
  content_type_options: nosniff
  ua_compatible: IE=edge
  xss_protection: 1; mode=block
  layout:
    smartphone:
      width: 600
