# ホスト別設定ファイル
#
# @package jp.co.b-shock.carrot3
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://carrot3.kapi.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: $2y$10$kqFRB02hpeyGe773G8v4d.hZsmuI0/uiz3AGe8yQB1bfhKdwEWv.O
author:
  password: $2y$10$kqFRB02hpeyGe773G8v4d.hZsmuI0/uiz3AGe8yQB1bfhKdwEWv.O
