root_url: http://carrot3.b-shock.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: $2y$10$kqFRB02hpeyGe773G8v4d.hZsmuI0/uiz3AGe8yQB1bfhKdwEWv.O
author:
  password: $2y$10$kqFRB02hpeyGe773G8v4d.hZsmuI0/uiz3AGe8yQB1bfhKdwEWv.O
